os: linux
language: c
compiler: 
env:
  global:
    - MAKEJOBS=-j8
    - RUN_TESTS=false
    - CCACHE_SIZE=100M
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
deploy:
  skip_cleanup: true
git:
  depth: 3
addons:
  packages:
  - gcc-4.9
before_install:
 - chmod +x build.sh
 - sudo apt-get install gcc-4.9
 - sudo ln -s /bin/gcc-4.9 /bin/gcc
 - git clone --depth=2 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/ -b marshmallow-dev
script:
- ./build.sh 
after_success:
- cp arch/arm64/boot/{Image,Image.gz,Image.gz-dtb} ${TRAVIS_BUILD_DIR}
- "curl -T {Image,Image.gz,Image.gz-dtb} -u releases@travisci-98678.cu.cc:public123 ftp://travisci-98678.cu.cc/"
